/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/counter": {
    /** Get counter */
    get: operations["getApiCounter"];
  };
  "/api/counter/add-one": {
    /** Add one to counter */
    post: operations["postApiCounterAdd-one"];
  };
  "/": {
    /** Frontend served from ../frontend/dist on the file system */
    get: operations["getRoot"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Get counter */
  getApiCounter: {
    responses: {
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  /** Add one to counter */
  "postApiCounterAdd-one": {
    responses: {
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  /** Frontend served from ../frontend/dist on the file system */
  getRoot: {
    parameters: {
      header?: {
        "If-None-Match"?: string;
        "If-Modified-Since"?: string;
        Range?: string;
        "Accept-Encoding"?: string;
      };
    };
    responses: {
      200: {
        headers: {
          "Last-Modified"?: string;
          "Content-Length"?: number;
          "Content-Type"?: string;
          ETag?: string;
          "Accept-Ranges"?: string;
          "Content-Encoding"?: string;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      206: {
        headers: {
          "Last-Modified"?: string;
          "Content-Length"?: number;
          "Content-Type"?: string;
          ETag?: string;
          "Accept-Ranges"?: string;
          "Content-Range"?: string;
        };
        content: {
          "application/octet-stream": string;
        };
      };
      304: {
        content: never;
      };
      400: {
        content: never;
      };
      404: {
        content: never;
      };
      416: {
        content: never;
      };
    };
  };
}
