/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/counter": {
    /** Get counter */
    get: operations["getCounter"];
  };
  "/counter/add-one": {
    /** Add one to counter */
    post: operations["postCounterAdd-one"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get counter */
  getCounter: {
    responses: {
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  /** Add one to counter */
  "postCounterAdd-one": {
    responses: {
      200: {
        content: never;
      };
    };
  };
}
