/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/counter": {
    /** Get counter */
    get: operations["getApiCounter"];
  };
  "/api/counter/add-one": {
    /** Add one to counter */
    post: operations["postApiCounterAdd-one"];
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /** Get counter */
  getApiCounter: {
    responses: {
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
  /** Add one to counter */
  "postApiCounterAdd-one": {
    responses: {
      200: {
        content: {
          "application/json": number;
        };
      };
    };
  };
}
